### ISSUE TITLE
Generate project from flutter-templates

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/ic-flutter-taher-toby#1]
## Why

Generating a project from our templates will give us the essential core to start off conveniently.

## Acceptance Criteria

Generate a project from flutter-templates, with the following parameters:

- **PACKAGE_NAME**: `"co.nimblehq.ic.flutter.taher.toby"`
- **PROJECT_NAME**: `"flutter_survey"`
- **APP_NAME**: `"Survey"`

Also, update the following files accordingly (after the generation):

- `CODEOWNERS`  → Add Toby, Taher, Lucas & Mike
- `PULL_REQUEST_TEMPLATE.md` → Update `flutter-templates` to `ic-flutter-taher-toby`
- `release_template.md` → Update `flutter-templates` to `ic-flutter-taher-toby`
- `README.md` → Update `flutter-templates` to `ic-flutter-taher-toby`
- `story_template.md` → Remove this, as it's unnecessary. 

## Design

N/A

## Resources

https://github.com/nimblehq/flutter-templates/tree/develop/template/android

**Comment by Shayokh144** [comment]
@Tuubz what do you think about adding our name in the `PACKAGE_NAME` like `co.nimblehq.icflutter.survey.tobytaher`? It will help use not getting conflict with other developers ic about the bundle id.

**Comment by Tuubz** [comment]
@Shayokh144 Updated ✅

**Comment by Shayokh144** [comment]
@Tuubz we can also update the name of the issue by adding type like some other issues you created already:
[Chore] Generate project from flutter-templates

**Comment by Tuubz** [comment]
Hmmm, but it's already indicated on the label (`type: chore`) that it's a chore, no? 

Feels a bit redundant, what do you think? 🙏

**Comment by Shayokh144** [comment]
@Tuubz you are right. Seems a bit redundant. I am good to go with current format.
