### ISSUE TITLE
[Integrate] As a user, I can log in with email and password

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/ic-flutter-taher-toby#10]
## Why

Handle response, after the user has authenticated with e-mail and password.

## Acceptance Criteria

When the user taps the log-in button, execute the request with e-mail and password:

- Show loading indicator, while the request is executing
- Show the home screen, if the request is successful
- Show an error message with the snack-bar, if the request failed
- Securely store `access_token`, `token_type` & `refresh_token` in cache, for later usage
- Add unit tests

## Design

N/A

## Resources

[Postman: API](https://documenter.getpostman.com/view/11835486/T1LJjTqj#5e3f9e18-3e0b-4c78-b71c-9b6daf905516)

**Comment by Shayokh144** [comment]
@Tuubz please add unit test at the `Acceptance Criteria` section. Same for other integrate stories.

**Comment by Tuubz** [comment]
@Shayokh144 Will do, I'll also add it for all the backend stories 👍
