### ISSUE TITLE
Set up CI to execute unit tests

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/ic-flutter-taher-toby#2]
## Why

In order to avoid any code smells, while maintaining code quality, a proper CI must be added.

**Note**: This has already been added in `test.yml`.

## Acceptance Criteria

- Every time a pull request is created or updated, the _unit_ tests must be run automatically. 
- The generated report must be visible in the PR and https://app.codecov.io/gh/nimblehq/ic-flutter-taher-toby/commits

**Note**: Don't need to run _UI_ tests just yet, this will be added later on. 

Once we have created all the screens, then we can start creating the UI test cases.

## Design

N/A

## Resources

https://app.codecov.io/gh

**Comment by Shayokh144** [comment]
@Tuubz Usually we show the code coverage report in the PR's conversation. I don't have idea about `codecov api`, can you explain a bit about the point `must be uploaded to https://app.codecov.io/gh/nimblehq/ic-flutter-taher-toby/commits`?

**Comment by Tuubz** [comment]
@Shayokh144 Aah yes, the code coverage report will show in the PR and also in https://app.codecov.io/gh/nimblehq/ic-flutter-taher-toby/commits 👍 I've updated the PR description, to make it more clear.

**Comment by Shayokh144** [comment]
thank you @Tuubz

**Comment by Shayokh144** [comment]
CI is already running. Code coverage is showing on both `PR description` and `Codecov` site. As a result issue is going to be closed.
<img width="674" alt="Screenshot 2023-03-22 at 4 16 23 PM" src="https://user-images.githubusercontent.com/13636465/226856221-36a89d59-275e-4d70-9b1f-c10ded696e7e.png">
<img width="1510" alt="Screenshot 2023-03-22 at 4 17 57 PM" src="https://user-images.githubusercontent.com/13636465/226856529-caabadcf-ca50-4852-951c-27072612601c.png">
